#! /bin/sh

set -e

case "$1" in
  install|upgrade)
    if [ -n "$2" ] && dpkg --compare-versions "$2" lt 3.0.9-1
    then
      ucf --purge /opt/borhan/app/configurations/php/conf.d/memcache.ini
    fi
    if test -e /opt/borhan/app/configurations/php/conf.d/memcache.ini
    then
      sed s/^\;extension/extension/ -i /opt/borhan/app/configurations/php/conf.d/memcache.ini
      dpkg-maintscript-helper mv_conffile /opt/borhan/app/configurations/php/conf.d/memcache.ini \
          /opt/borhan/app/configurations/php/mods-available/memcache.ini 3.0.9-1 -- "$@"
      rm -f /opt/borhan/app/configurations/php/conf.d/memcache.ini
    fi
    ;;
  abort-upgrade)
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
