#!/bin/bash
set -e
if [ "$1" != "remove" -a "$1" != "purge" ]; then
        exit 0
fi
a2dissite admin.conf apps.conf var.conf zzzborhan.conf zzzborhan.ssl.conf || true
rm -f /etc/cron.d/borhan-api
rm -f /etc/cron.d/borhan-cleanup
rm -f /etc/logrotate.d/borhan_api
rm -f /etc/logrotate.d/borhan_apache

