# Creates a borhan server from a standard centos-6.5 installation
# this will always create the latest borhan version using install scripts

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-6.7"
# set this to the IP addr you wish to set on the VM host
  config.vm.network "private_network", ip: "10.1.1.1"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.provision "file", source: "oflaDemo-r4472-java6.war", destination: "oflaDemo-r4472-java6.war"
  config.vm.provision "file", source: "borhan-install-config.sh", destination: "borhan-install-config.sh"
  config.vm.provision "shell", path: "borhan-install.sh"
end
