#!/bin/bash
BORHAN_GROUP=borhan
BORHAN_USER=borhan
APACHE_USER=www-data
BORHAN_PREFIX=/opt/borhan

if ! getent group $BORHAN_GROUP >/dev/null; then
        addgroup --system --force-badname --quiet $BORHAN_GROUP --gid 7373 
fi

if ! getent passwd $BORHAN_USER >/dev/null; then
        adduser --system --force-badname --quiet \
            --home $BORHAN_PREFIX --no-create-home \
            --shell /bin/bash \
    --uid 7373 \
            --group $BORHAN_GROUP
        usermod -c "Borhan server" $BORHAN_USER
	usermod -a -G www-data borhan
fi

if [ "$1" = "upgrade" ];then
	touch $BORHAN_PREFIX/bin/borhan-base-upgrading
fi
