#!/bin/sh
set -e
if [ "$1" = "remove" ] ;then
	rm -f /etc/borhan.d/system.ini
	rm -f /opt/borhan/app/alpha/web/api_v3
	rm -f /etc/logrotate.d/borhan_base
	# get rid of stray symlinks.
	find /opt/borhan/app -maxdepth 1 -name "*.lock" -exec rm {} \;
fi
