#!/bin/bash
ldconfig
if [ "$1" = "configure" ]; then
        . /usr/share/debconf/confmodule
        db_get 'borhan-nginx/nginx_hostname'
        if [ -z "$RET" ];then
                db_set 'borhan-nginx/nginx_hostname' "`hostname`"
        fi
        db_input critical 'borhan-nginx/nginx_hostname' || true
        db_go || true
        db_get 'borhan-nginx/nginx_hostname'
        VOD_PACKAGER_HOST=$RET

        db_input critical 'borhan-nginx/nginx_port' || true
        db_go || true
        db_get 'borhan-nginx/nginx_port'
        VOD_PACKAGER_PORT=$RET

        db_input critical 'borhan-nginx/rtmp_port' || true
        db_go || true
        db_get 'borhan-nginx/rtmp_port'
        RTMP_PORT=$RET


        db_get 'borhan-nginx/borhan_service_url'
        db_input critical 'borhan-nginx/borhan_service_url' || true
        db_go || true
        db_get 'borhan-nginx/borhan_service_url'
        WWW_HOST=$RET
	db_input critical borhan-nginx/is_ssl || true
	db_go || true
	db_get borhan-nginx/is_ssl
	IS_NGINX_SSL="$RET"
	if [ "$IS_NGINX_SSL" = 'true' ];then
		db_input critical 'borhan-nginx/nginx_ssl_port' || true
		db_go || true
		db_get 'borhan-nginx/nginx_ssl_port'
		VOD_PACKAGER_SSL_PORT=$RET

		db_input critical 'borhan-nginx/ssl_cert' || true
		db_go || true
		db_get 'borhan-nginx/ssl_cert'
		SSL_CERT=$RET

		db_input critical 'borhan-nginx/ssl_key' || true
		db_go || true
		db_get 'borhan-nginx/ssl_key'
		SSL_KEY=$RET
		sed -e "s#@VOD_PACKAGER_HOST@#$VOD_PACKAGER_HOST#g" -e "s#@VOD_PACKAGER_SSL_PORT@#$VOD_PACKAGER_SSL_PORT#g" -e "s#@SSL_CERT@#$SSL_CERT#g" -e "s#@SSL_KEY@#$SSL_KEY#g" /opt/borhan/nginx/conf/ssl.conf.template > /opt/borhan/nginx/conf/ssl.conf
	else
		touch /opt/borhan/nginx/conf/ssl.conf
	fi
        sed -e "s#@VOD_PACKAGER_HOST@#$VOD_PACKAGER_HOST#g" -e "s#@VOD_PACKAGER_PORT@#$VOD_PACKAGER_PORT#g" -e "s#@RTMP_PORT@#$RTMP_PORT#g" -e "s#@LOG_DIR@#/opt/borhan/log/nginx#" -e "s#@WWW_HOST@#$WWW_HOST#g" /opt/borhan/nginx/conf/nginx.conf.template > /opt/borhan/nginx/conf/nginx.conf
	sed -e 's#@STATIC_FILES_PATH@#/opt/borhan/nginx/static#g' /opt/borhan/nginx/conf/borhan.conf.template > /opt/borhan/nginx/conf/borhan.conf
        update-rc.d borhan-nginx defaults || true

fi
chown -R borhan /opt/borhan/log/nginx
service borhan-nginx reload 
