#!/bin/bash

BORHAN_FUNCTIONS_RC=/opt/borhan/bin/borhan-functions.rc
if [ ! -r "$BORHAN_FUNCTIONS_RC" ];then
        OUT="${BRIGHT_RED}ERROR:could not find $BORHAN_FUNCTIONS_RC so, exiting..${NORMAL}"
        echo -en $OUT
        exit 3
fi
. $BORHAN_FUNCTIONS_RC
RC_FILE=/etc/borhan.d/system.ini
if [ ! -r "$RC_FILE" ];then
        echo "${BRIGHT_RED}Could not find $RC_FILE so, exiting..${NORMAL}"
        exit 2
fi
. $RC_FILE
UI_CONF=`echo "select conf_file_path from ui_conf where tags like '%bmc_uploadWebCam%';"|mysql -u$DB1_USER -P$DB1_PORT -p$DB1_PASS $DB1_NAME -h$DB1_HOST --skip-column-names`
sed -i "s@{HOST_NAME}@$RED5_HOST@g" "$BASE_DIR/web/$UI_CONF"

if [ ! -d /usr/lib/red5/webapps/oflaDemo/streams ];then
        echo -e "${BRIGHT_RED}You need to install OflaDemo. Please follow instructions here:
https://github.com/borhan/platform-install-packages/blob/master/doc/install-borhan-redhat-based.md#configure-red5-server
Once done run dpkg-reconfigure borhan-red5 ${NORMAL}"
fi
if [ ! -L $BASE_DIR/web/content/webcam ];then
        ln -sf /usr/share/red5/webapps/oflaDemo/streams $BASE_DIR/web/content/webcam
fi


chown www-data /usr/share/red5/webapps/

